/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testrelocatedesctop_nativelib_CreateDescriptionFile */

#ifndef _Included_com_example_testrelocatedesctop_nativelib_CreateDescriptionFile
#define _Included_com_example_testrelocatedesctop_nativelib_CreateDescriptionFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testrelocatedesctop_nativelib_CreateDescriptionFile
 * Method:    NTFSDoc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_testrelocatedesctop_nativelib_CreateDescriptionFile_NTFSDoc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
